version: "3.8"

services:
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - alerts_data:/data  # Общий том для SQLite файла
    ports:
      - "5000:5000"
    restart: always

volumes:
  alerts_data:  # Том для хранения базы